LOAD DATA LOCAL INFILE "article.csv" INTO TABLE Article
  FIELDS TERMINATED BY "<>" ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE "field.csv" INTO TABLE Field
  FIELDS TERMINATED BY "<>" ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE "has_experience.csv" INTO TABLE Has_Experience
  FIELDS TERMINATED BY "<>" ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE "user.csv" INTO TABLE User
  FIELDS TERMINATED BY "<>" ENCLOSED BY '"'
  LINES TERMINATED BY "\n";

  LOAD DATA LOCAL INFILE "admin.csv" INTO TABLE Admin
  FIELDS TERMINATED BY "<>" ENCLOSED BY '"'
  LINES TERMINATED BY "\n";